"""initial schema

Revision ID: 396c81863418
Revises: 
Create Date: 2026-10-03 16:40:23.916190
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import ecosystem.db.models.types

revision = '396c81863418'
down_revision = None
branch_labels = None
depends_on = None


APPEND_ONLY_TABLES = ("audit_logs", "system_events", "transactions", "profit_records")


def upgrade() -> None:
    # pgvector must exist before agent_memory.embedding is created. Creating an
    # extension needs superuser rights, so a denied attempt is tolerated: the
    # bootstrap script (scripts/bootstrap_db.sh) installs it as postgres first.
    op.execute(
        """
        DO $$ BEGIN
            BEGIN
                CREATE EXTENSION IF NOT EXISTS vector;
            EXCEPTION WHEN insufficient_privilege THEN
                RAISE NOTICE 'vector extension not created (needs superuser); ensure bootstrap ran';
            END;
        END $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCESS', 'DENIED', 'ERROR', name='auditoutcome'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('benchmarks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('series', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmarks'))
    )
    op.create_index(op.f('ix_benchmarks_created_at'), 'benchmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_benchmarks_symbol'), 'benchmarks', ['symbol'], unique=False)
    op.create_table('generations',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'EVALUATING', 'COMPLETED', 'ARCHIVED', name='generationstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_generation_id', sa.UUID(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_generation_id'], ['generations.id'], name=op.f('fk_generations_parent_generation_id_generations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generations'))
    )
    op.create_index(op.f('ix_generations_created_at'), 'generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_generations_number'), 'generations', ['number'], unique=True)
    op.create_table('market_data_series',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('bar_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('volatility_regime', sa.String(length=24), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_series')),
    sa.UniqueConstraint('symbol', 'interval', 'source', name='uq_market_series_key')
    )
    op.create_index(op.f('ix_market_data_series_created_at'), 'market_data_series', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_series_symbol'), 'market_data_series', ['symbol'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metrics'))
    )
    op.create_index('ix_performance_metrics_scope_created', 'performance_metrics', ['scope', 'scope_id', 'created_at'], unique=False)
    op.create_table('research_questions',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_questions'))
    )
    op.create_index(op.f('ix_research_questions_created_at'), 'research_questions', ['created_at'], unique=False)
    op.create_index('ix_research_questions_status_priority', 'research_questions', ['status', 'priority'], unique=False)
    op.create_table('risk_limits',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('limit_type', sa.String(length=48), nullable=False),
    sa.Column('value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_limits')),
    sa.UniqueConstraint('scope', 'scope_id', 'name', name='uq_risk_limits_scope_name')
    )
    op.create_index(op.f('ix_risk_limits_created_at'), 'risk_limits', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'OBSERVER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('agents',
    sa.Column('codename', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('specialization', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', 'ARCHIVED', 'QUARANTINED', name='agentstatus'), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('parent_a_id', sa.UUID(), nullable=True),
    sa.Column('parent_b_id', sa.UUID(), nullable=True),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inherited_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_horizon', sa.String(length=32), nullable=False),
    sa.Column('research_priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creation_reason', sa.Text(), nullable=True),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('current_strategy_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_strategy_id'], ['strategies.id'], name='fk_agents_current_strategy_id_strategies', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_agents_generation_id_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_a_id'], ['agents.id'], name=op.f('fk_agents_parent_a_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_b_id'], ['agents.id'], name=op.f('fk_agents_parent_b_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('codename', name='uq_agents_codename')
    )
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index('ix_agents_generation_status', 'agents', ['generation_id', 'status'], unique=False)
    op.create_index(op.f('ix_agents_specialization'), 'agents', ['specialization'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('market_bars',
    sa.Column('series_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('spread_bps', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['market_data_series.id'], name=op.f('fk_market_bars_series_id_market_data_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_bars')),
    sa.UniqueConstraint('series_id', 'timestamp', name='uq_market_bars_series_time')
    )
    op.create_index('ix_market_bars_series_timestamp', 'market_bars', ['series_id', 'timestamp'], unique=False)
    op.create_table('accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('TREASURY_PROTECTED', 'TREASURY_TRADING', 'TREASURY_OPERATING', 'TREASURY_PROFIT', 'AGENT', name='accountkind'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('starting_capital', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('cash', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('reserved_capital', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('realized_profit', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('total_fees', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_accounts_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_kind'), 'accounts', ['kind'], unique=False)
    op.create_index('ix_accounts_kind_agent', 'accounts', ['kind', 'agent_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_events_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_events'))
    )
    op.create_index('ix_agent_events_agent_created', 'agent_events', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_events_created_at'), 'agent_events', ['created_at'], unique=False)
    op.create_table('agent_memory',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('OBSERVATION', 'RESEARCH', 'HYPOTHESIS', 'DECISION', 'EXPERIMENT_RESULT', 'STRATEGY_VERSION', 'DISCOVERY', 'FAILURE', 'LESSON', 'MARKET_CONDITION', 'RELATIONSHIP', name='memorykind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_type', sa.String(length=48), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_memory_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memory'))
    )
    op.create_index('ix_agent_memory_agent_kind', 'agent_memory', ['agent_id', 'kind'], unique=False)
    op.create_index(op.f('ix_agent_memory_created_at'), 'agent_memory', ['created_at'], unique=False)
    op.create_index('ix_agent_memory_embedding_hnsw', 'agent_memory', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_agent_memory_kind'), 'agent_memory', ['kind'], unique=False)
    op.create_table('agent_relationships',
    sa.Column('source_agent_id', sa.UUID(), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('interactions', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], name=op.f('fk_agent_relationships_source_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], name=op.f('fk_agent_relationships_target_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_relationships')),
    sa.UniqueConstraint('source_agent_id', 'target_agent_id', 'relation', name='uq_agent_relationships_edge')
    )
    op.create_index(op.f('ix_agent_relationships_created_at'), 'agent_relationships', ['created_at'], unique=False)
    op.create_table('hypotheses',
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('prior_confidence', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('posterior_confidence', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_hypotheses_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['research_questions.id'], name=op.f('fk_hypotheses_question_id_research_questions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    op.create_index(op.f('ix_hypotheses_agent_id'), 'hypotheses', ['agent_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_created_at'), 'hypotheses', ['created_at'], unique=False)
    op.create_table('strategies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'HYPOTHESIS', 'IMPLEMENTATION', 'BACKTEST', 'OUT_OF_SAMPLE', 'ROBUSTNESS', 'PAPER_TRADING', 'EVALUATION', 'RETIRED', 'REJECTED', name='strategystage'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('parent_strategy_id', sa.UUID(), nullable=True),
    sa.Column('asset_universe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_horizon', sa.String(length=32), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('creation_reason', sa.Text(), nullable=True),
    sa.Column('retired_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_strategies_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_strategy_id'], ['strategies.id'], name=op.f('fk_strategies_parent_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('slug', name=op.f('uq_strategies_slug'))
    )
    op.create_index(op.f('ix_strategies_agent_id'), 'strategies', ['agent_id'], unique=False)
    op.create_index('ix_strategies_agent_stage', 'strategies', ['agent_id', 'stage'], unique=False)
    op.create_index(op.f('ix_strategies_created_at'), 'strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategies_generation_number'), 'strategies', ['generation_number'], unique=False)
    op.create_index(op.f('ix_strategies_stage'), 'strategies', ['stage'], unique=False)
    op.create_table('system_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('AI', 'AGENT', 'RESEARCH', 'TRADE', 'RISK', 'ACCOUNT', 'SYSTEM', 'SECURITY', name='eventcategory'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_system_events_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_system_events_category_created', 'system_events', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('balances',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('available', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('reserved', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_balances_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balances')),
    sa.UniqueConstraint('account_id', 'currency', name='uq_balances_account_currency')
    )
    op.create_index(op.f('ix_balances_created_at'), 'balances', ['created_at'], unique=False)
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('cash', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('positions_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('total_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('peak_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('realized_profit', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('total_fees', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('last_valued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_portfolios_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_portfolios_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('agent_id', 'name', name='uq_portfolios_agent_name')
    )
    op.create_index(op.f('ix_portfolios_agent_id'), 'portfolios', ['agent_id'], unique=False)
    op.create_index(op.f('ix_portfolios_created_at'), 'portfolios', ['created_at'], unique=False)
    op.create_table('profit_records',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('amount', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_profit_records_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_profit_records_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_records'))
    )
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exit_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutation_reason', sa.Text(), nullable=True),
    sa.Column('creation_reason', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_strategy_versions_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['strategy_versions.id'], name=op.f('fk_strategy_versions_parent_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_versions_strategy_version')
    )
    op.create_index(op.f('ix_strategy_versions_content_hash'), 'strategy_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_strategy_versions_created_at'), 'strategy_versions', ['created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('strategy_version_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('BACKTEST', 'OUT_OF_SAMPLE', 'ROBUSTNESS', 'PAPER_TRADING', name='experimentstage'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ASSIGNED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='experimentstatus'), nullable=False),
    sa.Column('priority', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_experiments_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_experiments_hypothesis_id_hypotheses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_experiments_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_experiments_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('ix_experiments_agent_created', 'experiments', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_experiments_agent_id'), 'experiments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index('ix_experiments_status_stage', 'experiments', ['status', 'stage'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('average_cost', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('last_price', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('market_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('unrealized_pnl', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('realized_pnl', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_positions_portfolio_symbol')
    )
    op.create_index(op.f('ix_positions_created_at'), 'positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('trade_proposals',
    sa.Column('is_high_impact', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'TRANSFER', name='proposalaction'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('price', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('amount', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_RISK', 'RISK_REJECTED', 'PENDING_ACCOUNTING', 'ACCOUNTING_REJECTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'EXECUTED', 'EXECUTION_FAILED', 'CANCELLED', 'BLOCKED_EMERGENCY', name='proposalstatus'), nullable=False),
    sa.Column('risk_decision', sa.Enum('PASS', 'WARN', 'REJECT', name='riskdecision'), nullable=True),
    sa.Column('risk_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accounting_ok', sa.Boolean(), nullable=True),
    sa.Column('accounting_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_trade_proposals_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_trade_proposals_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_trade_proposals_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trade_proposals_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_proposals'))
    )
    op.create_index(op.f('ix_trade_proposals_agent_id'), 'trade_proposals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_created_at'), 'trade_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_proposals_status'), 'trade_proposals', ['status'], unique=False)
    op.create_table('transfer_proposals',
    sa.Column('source_account_id', sa.UUID(), nullable=True),
    sa.Column('destination_account_id', sa.UUID(), nullable=True),
    sa.Column('is_high_impact', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', 'TRANSFER', name='proposalaction'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('price', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('amount', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_RISK', 'RISK_REJECTED', 'PENDING_ACCOUNTING', 'ACCOUNTING_REJECTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'EXECUTED', 'EXECUTION_FAILED', 'CANCELLED', 'BLOCKED_EMERGENCY', name='proposalstatus'), nullable=False),
    sa.Column('risk_decision', sa.Enum('PASS', 'WARN', 'REJECT', name='riskdecision'), nullable=True),
    sa.Column('risk_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accounting_ok', sa.Boolean(), nullable=True),
    sa.Column('accounting_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transfer_proposals_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_transfer_proposals_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], name=op.f('fk_transfer_proposals_destination_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transfer_proposals_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], name=op.f('fk_transfer_proposals_source_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_transfer_proposals_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_proposals'))
    )
    op.create_index(op.f('ix_transfer_proposals_agent_id'), 'transfer_proposals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_transfer_proposals_created_at'), 'transfer_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_transfer_proposals_status'), 'transfer_proposals', ['status'], unique=False)
    op.create_table('approval_requests',
    sa.Column('proposal_kind', sa.Enum('TRADE', 'TRANSFER', name='proposalkind'), nullable=False),
    sa.Column('trade_proposal_id', sa.UUID(), nullable=True),
    sa.Column('transfer_proposal_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_RISK', 'RISK_REJECTED', 'PENDING_ACCOUNTING', 'ACCOUNTING_REJECTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'EXECUTED', 'EXECUTION_FAILED', 'CANCELLED', 'BLOCKED_EMERGENCY', name='proposalstatus'), nullable=False),
    sa.Column('is_high_impact', sa.Boolean(), nullable=False),
    sa.Column('confirmation_phrase', sa.String(length=64), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_approval_requests_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_approval_requests_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_proposal_id'], ['trade_proposals.id'], name=op.f('fk_approval_requests_trade_proposal_id_trade_proposals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_proposal_id'], ['transfer_proposals.id'], name=op.f('fk_approval_requests_transfer_proposal_id_transfer_proposals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index('ix_approval_requests_status_created', 'approval_requests', ['status', 'created_at'], unique=False)
    op.create_table('experiment_results',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('BACKTEST', 'OUT_OF_SAMPLE', 'ROBUSTNESS', 'PAPER_TRADING', name='experimentstage'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('deterministic_seed', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_results_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_results'))
    )
    op.create_index('ix_experiment_results_experiment', 'experiment_results', ['experiment_id', 'created_at'], unique=False)
    op.create_table('risk_events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.Enum('PASS', 'WARN', 'REJECT', name='riskdecision'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='riskseverity'), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('observed_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=True),
    sa.Column('limit_value', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_risk_events_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['trade_proposals.id'], name=op.f('fk_risk_events_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index('ix_risk_events_decision_created', 'risk_events', ['decision', 'created_at'], unique=False)
    op.create_table('execution_records',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposal_kind', sa.Enum('TRADE', 'TRANSFER', name='proposalkind'), nullable=False),
    sa.Column('trade_proposal_id', sa.UUID(), nullable=True),
    sa.Column('transfer_proposal_id', sa.UUID(), nullable=True),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('adapter', sa.Enum('SIMULATED', 'PAPER_TRADING', 'TESTNET', 'PRODUCTION', name='adapterkind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIAL', 'FAILED', 'REJECTED', name='executionstatus'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('requested_quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('filled_quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('fill_price', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('fee', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('slippage', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_execution_records_approval_request_id_approval_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_proposal_id'], ['trade_proposals.id'], name=op.f('fk_execution_records_trade_proposal_id_trade_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_proposal_id'], ['transfer_proposals.id'], name=op.f('fk_execution_records_transfer_proposal_id_transfer_proposals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_records'))
    )
    op.create_index(op.f('ix_execution_records_status'), 'execution_records', ['status'], unique=False)
    op.create_index('ix_execution_records_status_created', 'execution_records', ['status', 'created_at'], unique=False)
    op.create_table('transactions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('quantity', ecosystem.db.models.types.NumericAsDecimal(precision=28, scale=12), nullable=False),
    sa.Column('price', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('gross_amount', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('fee', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('net_amount', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('balance_after', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('realized_pnl', ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8), nullable=False),
    sa.Column('execution_record_id', sa.UUID(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_transactions_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_record_id'], ['execution_records.id'], name=op.f('fk_transactions_execution_record_id_execution_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index('ix_transactions_account_created', 'transactions', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_kind'), 'transactions', ['kind'], unique=False)
    op.create_index('ix_transactions_portfolio_created', 'transactions', ['portfolio_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement. A trigger is used rather than a GRANT so the
    # rule holds even for the application's own database role: no code path can
    # rewrite financial or audit history.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ecosystem_block_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION ecosystem_block_mutation();
            """
        )


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS ecosystem_block_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_portfolio_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_kind'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index('ix_transactions_account_created', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_execution_records_status_created', table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_status'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index('ix_risk_events_decision_created', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_experiment_results_experiment', table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_index('ix_approval_requests_status_created', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_transfer_proposals_status'), table_name='transfer_proposals')
    op.drop_index(op.f('ix_transfer_proposals_created_at'), table_name='transfer_proposals')
    op.drop_index(op.f('ix_transfer_proposals_agent_id'), table_name='transfer_proposals')
    op.drop_table('transfer_proposals')
    op.drop_index(op.f('ix_trade_proposals_status'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_created_at'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_agent_id'), table_name='trade_proposals')
    op.drop_table('trade_proposals')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_created_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_experiments_status_stage', table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_agent_id'), table_name='experiments')
    op.drop_index('ix_experiments_agent_created', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_strategy_versions_created_at'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_content_hash'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_table('profit_records')
    op.drop_index(op.f('ix_portfolios_created_at'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_agent_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_balances_created_at'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_index('ix_system_events_category_created', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_strategies_stage'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_generation_number'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_at'), table_name='strategies')
    op.drop_index('ix_strategies_agent_stage', table_name='strategies')
    op.drop_index(op.f('ix_strategies_agent_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_hypotheses_created_at'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_agent_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_agent_relationships_created_at'), table_name='agent_relationships')
    op.drop_table('agent_relationships')
    op.drop_index(op.f('ix_agent_memory_kind'), table_name='agent_memory')
    op.drop_index('ix_agent_memory_embedding_hnsw', table_name='agent_memory', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_agent_memory_created_at'), table_name='agent_memory')
    op.drop_index('ix_agent_memory_agent_kind', table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_events_created_at'), table_name='agent_events')
    op.drop_index('ix_agent_events_agent_created', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('ix_accounts_kind_agent', table_name='accounts')
    op.drop_index(op.f('ix_accounts_kind'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_market_bars_series_timestamp', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_specialization'), table_name='agents')
    op.drop_index('ix_agents_generation_status', table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_risk_limits_created_at'), table_name='risk_limits')
    op.drop_table('risk_limits')
    op.drop_index('ix_research_questions_status_priority', table_name='research_questions')
    op.drop_index(op.f('ix_research_questions_created_at'), table_name='research_questions')
    op.drop_table('research_questions')
    op.drop_index('ix_performance_metrics_scope_created', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_market_data_series_symbol'), table_name='market_data_series')
    op.drop_index(op.f('ix_market_data_series_created_at'), table_name='market_data_series')
    op.drop_table('market_data_series')
    op.drop_index(op.f('ix_generations_number'), table_name='generations')
    op.drop_index(op.f('ix_generations_created_at'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_benchmarks_symbol'), table_name='benchmarks')
    op.drop_index(op.f('ix_benchmarks_created_at'), table_name='benchmarks')
    op.drop_table('benchmarks')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
