"""add portfolio reserved_capital

Revision ID: 864c55c281d8
Revises: 16af3915b753
Create Date: 2026-10-03 17:11:11.933014
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import ecosystem.db.models.types


revision = '864c55c281d8'
down_revision = '16af3915b753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'portfolios',
        sa.Column(
            'reserved_capital',
            ecosystem.db.models.types.NumericAsDecimal(precision=24, scale=8),
            nullable=False,
            server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'reserved_capital')
    # ### end Alembic commands ###
